# Close stale issues after 30 days
# Interaction with a new issue

name: Manage Issues

on:
  issues:
    types: 
      - opened
    schedule:
      - cron: "0 4 * * *" #10 pm en mexico

jobs:

  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for
           30 days with no activity"
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }} 

  greeting_on_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Greet new issue
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thanks for the question. We'll review it ASAP"

   
